AVX-7632: use PostAPI and GetAPI
AviatrixSystems/terraform-provider-aviatrix pull request #1078
Opened 2021-08-02 12:32 UTC by shuoliugit

2021-08-04 23:38 UTC, CyrusJavan reviewed
Went through first 13 files aws_guard_duty.go -> firenet.go. 

Will continue tomorrow.

2021-08-04 23:38 UTC, CyrusJavan commented on goaviatrix/firenet.go
> +		form["inspection"] = "false"
Can simplify to 
```go
"inspection": strconv.FormatBool(fireNet.Inspection),
```

2021-08-04 23:38 UTC, CyrusJavan commented on goaviatrix/firenet.go
>  	}
Can simplify to 
```go
"firewall_egress": strconv.FormatBool(fireNet. FirewallEgress),
```

2021-08-04 23:38 UTC, CyrusJavan commented on goaviatrix/firenet.go
> +			if strings.Contains(reason, "configuration not found") {
Looks like the original was `configuration not changed`

2021-08-05 18:31 UTC, CyrusJavan requested changes
All files reviewed 👍

2021-08-05 18:31 UTC, CyrusJavan commented on goaviatrix/firewall_instance.go
> +	err := c.GetAPI(&data, form["action"], form, BasicCheck)
Cannot use GetAPI here because this is a modifying operation and GetAPI has built in retries.

2021-08-05 18:31 UTC, CyrusJavan commented on goaviatrix/firewall_instance.go
> +		"vpc_id": firewallInstance.VpcID,
Missing firewall_id from the original.

2021-08-05 18:31 UTC, CyrusJavan commented on goaviatrix/fqdn.go
> +		"gw_name":  gateway.GwName,
Looks like this was gateway_name in the original

2021-08-05 18:31 UTC, CyrusJavan commented on goaviatrix/gateway.go
> -			gw.AllocateNewEipRead = gw.AllocateNewEipReadPtr == nil || *gw.AllocateNewEipReadPtr
Why do we remove this logic?

2021-08-05 18:31 UTC, CyrusJavan commented on goaviatrix/profile.go
> -		panic("boom")
😂

2021-08-05 19:32 UTC, shuoliugit commented on goaviatrix/firewall_instance.go
> +	err := c.GetAPI(&data, form["action"], form, BasicCheck)
But we need to use data.Results later.

```
	if data.Results.FirewallID != "" {
		return data.Results.FirewallID, nil
	}
```

2021-08-05 20:11 UTC, shuoliugit commented on goaviatrix/gateway.go
> -			gw.AllocateNewEipRead = gw.AllocateNewEipReadPtr == nil || *gw.AllocateNewEipReadPtr
it's from one of Matthew's PR, not sure why it's showing up here.

https://github.com/AviatrixSystems/terraform-provider-aviatrix/pull/1076/files

2021-08-05 20:46 UTC, CyrusJavan commented on goaviatrix/firewall_instance.go
> +	err := c.GetAPI(&data, form["action"], form, BasicCheck)
I think we have 2 options:
1. Modify GetAPI to somehow make the retries configurable, e.g. boolean param enableRetries or some other way
2. Leave this function as it was.

What do you think?

2021-08-05 20:48 UTC, CyrusJavan commented on goaviatrix/gateway.go
> -			gw.AllocateNewEipRead = gw.AllocateNewEipReadPtr == nil || *gw.AllocateNewEipReadPtr
Hmm something got messed up in the rebase I guess. You can just add it back then.

2021-08-05 21:37 UTC, CyrusJavan approved these changes
Great stuff Shuo!

2021-08-05 23:28 UTC, zhiqiangjin approved these changes

2021-08-05 23:28 UTC, merged