AVX-14601: Update documentation for gateway, spoke gateway and transi…
AviatrixSystems/terraform-provider-aviatrix pull request #1099
Opened 2021-08-25 22:02 UTC by mlin-aviatrix

…t gateway vpc_id error

2021-08-25 23:32 UTC, shuoliugit submitted a review, later dismissed

2021-08-26 18:38 UTC, inc1t3Ful requested changes
Technically, this warning isn't accurate, right? Because gateway itself will not throw an error in the apply. It only throws an error if there are dependent resources after that gateway. 

The error gets thrown because the downline resources that depend on the `vpc_id` of the gateway sees that the values have changed after the first apply.

Also, I think we should keep it consistent and be clear with naming conventions. For Azure, its a VNet.

2021-08-27 22:30 UTC, inc1t3Ful approved these changes

2021-08-30 16:28 UTC, zhiqiangjin approved these changes

2021-08-30 16:28 UTC, merged