AVX-16372: add support for approved_learned_cidrs
AviatrixSystems/terraform-provider-aviatrix pull request #1141
Opened 2021-11-11 20:34 UTC by shuoliugit

2021-11-12 22:21 UTC, zhiqiangjin requested changes

2021-11-12 22:21 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_gateway.go
> +		d.Set("approved_learned_cidrs", transitAdvancedConfig.ApprovedLearnedCidrs)
TypeSet is no a primitive type. May do a check if this set is successfully.

2021-11-12 22:21 UTC, zhiqiangjin commented on docs/resources/aviatrix_transit_gateway.md
> +* `approved_learned_cidrs` - (Optional) A list of approved learned CIDRs. Only valid when `enable_learned_cidrs_approval` is set to true. Example: ["10.250.0.0/16", "10.251.0.0/16"]. Available as of
A set of.

2021-11-12 22:21 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_gateway.go
> +				Optional:    true,
Is it computed also?

2021-11-16 21:32 UTC, shuoliugit commented on aviatrix/resource_aviatrix_transit_gateway.go
> +				Optional:    true,
This is not computed.

2021-11-17 17:04 UTC, zhiqiangjin approved these changes

2021-11-17 17:04 UTC, merged