AVX-14880: add deprecation message to aws_tgw_security_domain_connection
AviatrixSystems/terraform-provider-aviatrix pull request #1154
Opened 2021-11-19 15:13 UTC by shuoliugit

2021-11-24 00:28 UTC, mlin-aviatrix submitted a review, later dismissed

2021-11-24 02:47 UTC, zhiqiangjin requested changes

2021-11-24 02:47 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_aws_tgw_security_domain_connection.go
> +		DeprecationMessage:   "Resource 'aviatrix_aws_tgw_security_domain_connection' will be deprecated in future release. Please use resource 'aviatrix_aws_tgw_peering_domain_conn' instead.",
Maybe " in future releases" or " in a future release"?

2021-11-24 02:47 UTC, zhiqiangjin commented on docs/resources/aviatrix_aws_tgw_security_domain_connection.md
> +!> **WARNING:** Resource 'aviatrix_aws_tgw_security_domain_connection' will be deprecated in future release. Please use resource 'aviatrix_aws_tgw_peering_domain_conn' instead.
Same.

2021-11-30 00:00 UTC, zhiqiangjin approved these changes

2021-11-30 00:00 UTC, merged