AVX-14578: Add new resource aviatrix_transit_cloudn_conn
AviatrixSystems/terraform-provider-aviatrix pull request #1162
Opened 2021-11-30 20:28 UTC by mlin-aviatrix

2021-12-01 21:03 UTC, zhiqiangjin requested changes

2021-12-01 21:03 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_cloudn_conn.go
> +				ForceNew:    true,
Give it a default value. Be consistent with GUI.

2021-12-01 21:03 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_cloudn_conn.go
> +				Optional:    true,
Give a default value. Be consistent with GUI.

2021-12-01 21:03 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_cloudn_conn.go
> +				Type:        schema.TypeBool,
Same.

2021-12-01 21:03 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_cloudn_conn.go
> +				Type:        schema.TypeBool,
Same.

2021-12-01 21:03 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_cloudn_conn.go
> +				Type:        schema.TypeBool,
Same.

2021-12-01 21:03 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_cloudn_conn.go
> +				Optional:    true,
Same.

2021-12-01 21:03 UTC, zhiqiangjin commented on docs/resources/aviatrix_transit_cloudn_conn.md
> +  cloudn_neighbor_as_num  = "65005"
One space between "as_num" and "=".

2021-12-02 15:01 UTC, shuoliugit approved these changes

2021-12-02 22:01 UTC, zhiqiangjin approved these changes

2021-12-02 22:01 UTC, merged