AVX-16834: support updating remote_subnet, add diff suppress func
AviatrixSystems/terraform-provider-aviatrix pull request #1163
Opened 2021-12-01 22:15 UTC by shuoliugit

This PR also fixes AVX-16553.

2021-12-01 22:45 UTC, mlin-aviatrix requested changes

2021-12-01 22:45 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_transit_external_device_conn.go
> +			return fmt.Errorf("could not update transit external device conn remote subnet during update: %v", err)
The message repeats update twice. You don't need "during update" at the end.

2021-12-02 17:49 UTC, mlin-aviatrix approved these changes

2021-12-02 18:25 UTC, zhiqiangjin approved these changes

2021-12-02 18:26 UTC, merged