AVX-16640: use file content of certificates
AviatrixSystems/terraform-provider-aviatrix pull request #1234
Opened 2022-03-08 19:37 UTC by shuoliugit

2022-03-14 18:21 UTC, mlin-aviatrix requested changes

2022-03-14 18:21 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_controller_config.go
> +				return fmt.Errorf("problem trying to disable imported certs to prepare for importing new certs: %v", err)
The wording for this error seems a little weird. Maybe something like `could not disable imported certs...` is better.

2022-03-14 18:21 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_controller_config.go
> +				return fmt.Errorf("problem trying to disable imported certs to prepare for importing new certs: %v", err)
Same as above

2022-03-15 17:38 UTC, zhiqiangjin approved these changes

2022-03-15 17:59 UTC, mlin-aviatrix approved these changes

2022-03-15 18:00 UTC, merged