AVX-20931: rename security domain to network domain
AviatrixSystems/terraform-provider-aviatrix pull request #1250
Opened 2022-04-08 23:38 UTC by shuoliugit

2022-04-13 02:32 UTC, inc1t3Ful requested changes

2022-04-13 02:32 UTC, inc1t3Ful commented on docs/guides/migrating_from_security_domain_to_network_domain.md
> +
Missing mention of the actual TF provider version in which is relevant to Controller 6.7+

2022-04-13 02:32 UTC, inc1t3Ful commented on docs/guides/migrating_from_security_domain_to_network_domain.md
> +  - Please set attribute `manage_security_domain` to false, and use the standalone resource **aviatrix_aws_tgw_network_domain** instead.
I like that the migration steps are on a per-resource case. That being said, its important to note down in the doc that there are 2 scenarios here:

1. using in-line `security_domain {}` aka not migrated at all
2. `manage_security_domain` is already set to false, and they are using the **aviatrix_aws_tgw_security_domain** resource already

Will need explicit instructions for these scenarios- if its repetitive, you can also refer the instructions to something already mentioned below

2022-04-13 02:32 UTC, inc1t3Ful commented on docs/guides/migrating_from_security_domain_to_network_domain.md
> +  3. Import the existing infrastructures to the resources.
Keep consistent syntax. eg.`security_domain` instead of "security_domain" etc.

Might be a good idea to include a sub-bullet point with an example command (or have it doc link to official Hashicorp docs detailing what `terraform state rm` is etc.

2022-04-13 02:32 UTC, inc1t3Ful commented on docs/resources/aviatrix_aws_tgw_connect.md
> +
"Either" `security_domain_name` or `network_domain_name` must be configured.

2022-04-13 02:32 UTC, inc1t3Ful commented on docs/resources/aviatrix_aws_tgw_directconnect.md
> +  network_domain_name        = "my-sdn-1"
nitpicking, but the actual value here still says 'sdn' , which would refer to 'security domain'

2022-04-13 02:32 UTC, inc1t3Ful commented on docs/resources/aviatrix_aws_tgw_directconnect.md
> +!> **WARNING:** Attribute `security_domain_name` will be deprecated in future releases. Please use the attribute `network_domain_name` instead. One of `security_domain_name` or `network_domain_name`
Same comment as previous. "Either"

2022-04-13 02:32 UTC, inc1t3Ful commented on docs/resources/aviatrix_aws_tgw_security_domain.md
> +!> **WARNING:** Resource 'aviatrix_aws_tgw_security_domain' will be deprecated in future releases. Please use resource 'aviatrix_aws_tgw_network_domain' instead.
Bold or use `code` block for the resource instead of quotes

2022-04-13 02:32 UTC, inc1t3Ful commented on docs/resources/aviatrix_aws_tgw_vpc_attachment.md
> +!> **WARNING:** Attribute `security_domain_name` will be deprecated in future releases. Please use the attribute `network_domain_name` instead. One of `security_domain_name` or `network_domain_name`
Either (same as other comments)

2022-04-14 17:24 UTC, inc1t3Ful requested changes
LGTM- just fix number list

2022-04-14 17:24 UTC, inc1t3Ful commented on docs/guides/migrating_from_security_domain_to_network_domain.md
> +  2. Import the existing infrastructures to the renamed resources.
the numbers are off

2022-04-14 21:07 UTC, inc1t3Ful submitted a review, later dismissed

2022-04-14 21:18 UTC, mlin-aviatrix requested changes

2022-04-14 21:18 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_aws_tgw_network_domain.go
> +		return diag.Errorf("could not create security domain: %v", err)
Should be network domain

2022-04-15 16:34 UTC, mlin-aviatrix approved these changes

2022-04-15 17:56 UTC, zhiqiangjin approved these changes

2022-04-15 17:56 UTC, merged