AVX-21420: add support for copilot sg mgmt
AviatrixSystems/terraform-provider-aviatrix pull request #1300
Opened 2022-05-23 18:54 UTC by shuoliugit

This is a feature for 6.8.

2022-06-16 23:09 UTC, zhiqiangjin requested changes

2022-06-16 23:09 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_copilot_security_group_management.go
> +		return diag.Errorf("'zone' is required and valid for GCP, 'region' must be emtpy")
Please rephrase this error message.

2022-06-16 23:09 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_copilot_security_group_management.go
> +		log.Printf("[DEBUG] Looks like an import, no name received. Import Id is %s", id)
This error message is not right.

2022-06-16 23:09 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_copilot_security_group_management_test.go
> +			return fmt.Errorf("copilot security group management not found: %s", resourceName)
Please work on this error message.

2022-06-16 23:09 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_copilot_security_group_management_test.go
> +			return fmt.Errorf("could not find copilot security group management")
Please update this error message.

2022-06-16 23:09 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_copilot_security_group_management_test.go
> +			return fmt.Errorf("copilot security group management still exists")
This error message is not right either.

2022-06-23 19:10 UTC, mlin-aviatrix requested changes

2022-06-23 19:10 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_copilot_security_group_management_config.go
> +				log.Printf("copilot security group management is already disabled")
I feel like it shouldn't be an error to call the disable API when it is already disabled. For Private Mode, I check the error message in the `CheckFunc` and return nil if it is already disabled.

2022-06-23 19:10 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_copilot_security_group_management_config.go
> +			log.Printf("copilot security group management is already disabled")
Same.

2022-06-23 19:10 UTC, mlin-aviatrix commented on goaviatrix/copilot_security_group_management_config.go
> +	err := c.PostAPIContext2(ctx, nil, copilotSecurityGroupManagementConfig.Action, copilotSecurityGroupManagementConfig, BasicCheck)
Just `return c.PostAPIContext2(...)`

2022-06-23 21:02 UTC, mlin-aviatrix approved these changes

2022-06-23 21:54 UTC, zhiqiangjin approved these changes

2022-06-23 21:54 UTC, merged