AVX-23092: add support for Edge as a Spoke
AviatrixSystems/terraform-provider-aviatrix pull request #1315
Opened 2022-06-04 16:27 UTC by shuoliugit

2022-06-16 23:13 UTC, zhiqiangjin requested changes

2022-06-16 23:13 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_edge_spoke.go
> +				Description: "WAN interface IP / prefix.",
IP/prefix.

2022-06-16 23:13 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_edge_spoke.go
> +				Description: "LAN interface IP / prefix.",
Same.

2022-06-16 23:13 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_edge_spoke.go
> +				Description: "Management egress gateway IP / prefix.",
Same.

2022-06-16 23:13 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_edge_spoke.go
> +				Description: "Management interface IP / prefix.",
Same.

2022-06-22 19:50 UTC, mlin-aviatrix approved these changes, later dismissed

2022-06-22 19:50 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_edge_spoke.go
> +				Description: "Approved learned CIDRs for BGP Spoke Gateway. Available as of provider version R2.21+.",
Don't need the last part `Available as of provider version...`

2022-06-22 19:50 UTC, mlin-aviatrix commented
I meant to request changes instead of approve. There is one small change.

2022-06-23 19:15 UTC, mlin-aviatrix approved these changes, later dismissed

2022-06-23 22:15 UTC, zhiqiangjin approved these changes

2022-06-23 22:15 UTC, merged