AVX-21299: add support for EaaS transit attachment
AviatrixSystems/terraform-provider-aviatrix pull request #1316
Opened 2022-06-06 12:31 UTC by shuoliugit

2022-06-22 20:05 UTC, mlin-aviatrix requested changes

2022-06-22 20:05 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_edge_spoke_transit_attachment_test.go
> +		os.Getenv("EDGE_SPOKE_NAME"))
I think we should check that `EDGE_SPOKE_NAME` is set in the PreCheck above.

2022-06-22 20:09 UTC, mlin-aviatrix requested changes

2022-06-22 20:09 UTC, mlin-aviatrix commented on docs/resources/aviatrix_edge_spoke_transit_attachment.md
> +* `spoke_prepend_as_path` - (Optional) Connection based AS Path Prepend. Can only use the gateway's own local AS number, repeated up to 25 times. Applies on spoke_gateway_name.
It might be more accurate to say `Applies on the Edge as a Spoke.`

2022-06-22 20:09 UTC, mlin-aviatrix commented on docs/resources/aviatrix_edge_spoke_transit_attachment.md
> +* `transit_prepend_as_path` - (Optional) Connection based AS Path Prepend. Can only use the gateway's own local AS number, repeated up to 25 times. Applies on transit_gateway_name.
It might be more accurate to say `Applies on the Transit Gateway.`

2022-06-23 19:20 UTC, mlin-aviatrix approved these changes, later dismissed

2022-06-23 21:55 UTC, zhiqiangjin submitted a review, later dismissed

2022-06-23 22:28 UTC, zhiqiangjin approved these changes

2022-06-23 22:28 UTC, merged