AVX-24635: EaaS BGP over LAN ext dev conn
AviatrixSystems/terraform-provider-aviatrix pull request #1329
Opened 2022-06-16 20:51 UTC by shuoliugit

2022-06-22 20:04 UTC, mlin-aviatrix requested changes

2022-06-22 20:04 UTC, mlin-aviatrix commented on test-infra/variables.tf
> +variable "edge_spoke_site_id" {}
What is this variable used for?

2022-06-22 20:04 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn_test.go
> +	`, os.Getenv("EDGE_SPOKE_SITE_ID"), rName, os.Getenv("EDGE_SPOKE_NAME"))
I think we should check that these environment variables are set in the PreCheck above.

2022-06-22 21:13 UTC, shuoliugit commented on test-infra/variables.tf
> +variable "edge_spoke_site_id" {}
That's the "VPC ID" for EaaS. In order to pass the test, EaaS has to be up. Some manual work is required to make an EaaS up, so we have to prepare a running EaaS and provide these required variables.

2022-06-23 19:22 UTC, mlin-aviatrix submitted a review, later dismissed

2022-06-23 22:40 UTC, zhiqiangjin approved these changes

2022-06-23 22:41 UTC, merged