AVX-25689: Add jumbo frame support for bgp/GRE tunnels
AviatrixSystems/terraform-provider-aviatrix pull request #1357
Opened 2022-07-16 06:15 UTC by zhiqiangjin

2022-07-16 12:27 UTC, shuoliugit approved these changes, later dismissed

2022-07-16 19:12 UTC, mlin-aviatrix submitted a review, later dismissed

2022-07-18 17:26 UTC, inc1t3Ful requested changes

2022-07-18 17:26 UTC, inc1t3Ful commented on docs/resources/aviatrix_transit_external_device_conn.md
> +* `enable_jumbo_frame` - (Optional)	Enable Jumbo Frame for the transit external device connection. Only valid with 'GRE' tunnels under 'bgp' connection. Requires transit to be jumbo frame and insane
remove the extra spaces after (Optional)

2022-07-18 17:37 UTC, inc1t3Ful approved these changes

2022-07-18 17:38 UTC, merged