AVX-27861: Add documentation for gateway group
AviatrixSystems/terraform-provider-aviatrix pull request #1472
Opened 2022-11-08 21:36 UTC by zhiqiangjin

2022-11-08 22:06 UTC, inc1t3Ful requested changes

2022-11-08 22:06 UTC, inc1t3Ful commented on docs/guides/introduction_to_gateway_group.md
> +As of Controller version 7.0+ and provider version 3.0.0+, gateway group feature will be introduced. Gateway group feature allows creation of multiple ha gateways under the same primary gateway. Only
should capitalize Gateway Group since its the feature name.

The Gateway Group feature allows for better horizontal scaling by moving from the current "primary + HA" gateway-pair model, to support a gateway grouping, represented by a "primary + N number of HA gateways".  The Gateway Group feature allows for users to create N number of HA gateways under a primary gateway.

For 7.0 release, only spoke gateways will be supported and HA gateways can only be created sequentially (one by one). In future releases, transit gateways and regular gateways will support this feature as well, and restrictions will be removed.

2022-11-08 22:06 UTC, inc1t3Ful commented on docs/guides/introduction_to_gateway_group.md
> +As in Controller version 7.0, a new resource aviatrix_spoke_ha_gateway is added to be used for Spoke HA Gateway creation. In order to be able to use the new resource, attribute `network_domain` needs
In Controller 7.0 and provider version 3.0, a new resource **aviatrix_spoke_ha_gateway** has been added to support spoke HA gateway creation.

In order to be able to use this new resource, the attribute `manage_ha_gateway` must be set to false in **aviatrix_spoke_gateway**; this will mark the spoke gateway to be used only as the primary.

(Should we mention future plans on the deprecation of this attribute? In order to push users to move to gateway groups?)

2022-11-09 06:45 UTC, jingzh66 reviewed
This is additional document besides resource aviatrix_spoke_ha_gateway, right?
Overall looks good.

2022-11-09 06:45 UTC, jingzh66 commented on docs/guides/introduction_to_gateway_group.md
> +**aviatrix_spoke_gateway**; this will mark the spoke gateway to be used only as the primary.
This line is not very clear to me.

2022-11-09 06:45 UTC, jingzh66 commented on docs/guides/introduction_to_gateway_group.md
> +    - Please set attribute `manage_ha_gateway` to false, and do a "terraform refresh" to set its value to the state file and remove Spoke HA gateway status from the state file
Do you need to remove ha_xxx parameters as well from aviatrix_spoke_gateway resource?

2022-11-09 18:08 UTC, inc1t3Ful approved these changes

2022-11-09 22:21 UTC, merged

2022-11-10 00:09 UTC, jzhuavtx commented on docs/guides/introduction_to_gateway_group.md
> +In future releases, transit gateways and regular gateways will support this feature as well, and restrictions will be
this will be for transit and spoke only, no plan for regular gateways

2022-11-10 01:33 UTC, jingzh66 reviewed
Should we add suggestion to create dependency if customer has more than 1 ha gateway? Same dependency to attach spoke to transit