AVX-37485: add resource symmetric_routing_config
AviatrixSystems/terraform-provider-aviatrix pull request #1688
Opened 2023-03-24 23:49 UTC by shuoliugit

2023-03-29 16:24 UTC, zhiqiangjin requested changes

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +			"enable_symmetric_routing": {
boolean attribute should have a default value.

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +				Description: "Enable symmetric routing.",
Please update description.

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +				Description: "Gateway name.",
Update description as well.

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +		status, _ := client.GetSymmetricRoutingStatus(ctx, gwName)
Is the status per gateway?

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +		status, _ := client.GetSymmetricRoutingStatus(ctx, gwName)
What will the output be to enable it even it is already enabled?

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +		} else {
Here same: what will the output be to disable it even it is disabled already?

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +				return diag.Errorf("failed to disable symmetric routing: %s", err)
If it is per gateway, maybe add the gateway into error message.

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +	} else if strings.Contains(status, "disabled") {
else {
  set false
}

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +				return diag.Errorf("failed to enable symmetric routing: %s", err)
Maybe add something like "in update" to show it fails in Update instead of Create.

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +				return diag.Errorf("failed to disable symmetric routing: %s", err)
Same.

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +		return diag.Errorf("could not delete symmetric routing: %v", err)
Same. Give a clear error message to show it fails at Delete.

2023-03-29 16:24 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_symmetric_routing_config_test.go
> +}
Should be consistent with the indent format. Please compare with other test resources.

2023-03-29 16:24 UTC, zhiqiangjin commented on docs/resources/aviatrix_symmetric_routing_config.md
> +  Creates and manages the configuration of symmetric routing
If per gateway, mention the gateway.

2023-03-29 16:24 UTC, zhiqiangjin commented on docs/resources/aviatrix_symmetric_routing_config.md
> +The **aviatrix_symmetric_routing_config** resource allows management of symmetric routing configuration.
Same.

2023-03-29 16:24 UTC, zhiqiangjin commented on docs/resources/aviatrix_symmetric_routing_config.md
> +  gw_name                  = "gateway"
Use a better gateway name in stead of "gateway".

2023-03-29 16:24 UTC, zhiqiangjin commented on docs/resources/aviatrix_symmetric_routing_config.md
> +### Required
Remove "### Required" if it does not exist in other resource markdowns.

2023-03-29 17:15 UTC, shuoliugit commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +		status, _ := client.GetSymmetricRoutingStatus(ctx, gwName)
> Is the status per gateway?

yes

2023-03-29 17:15 UTC, shuoliugit commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +		status, _ := client.GetSymmetricRoutingStatus(ctx, gwName)
> What will the output be to enable it even it is already enabled?

If it's enabled, it's ok and shouldn't error out.

2023-03-29 17:18 UTC, shuoliugit commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +		} else {
> Here same: what will the output be to disable it even it is disabled already?

Same. If it's disabled, it's ok and shouldn't error out.

2023-03-29 18:14 UTC, shuoliugit commented on aviatrix/resource_aviatrix_symmetric_routing_config_test.go
> +}
> Should be consistent with the indent format. Please compare with other test resources.

The format looks correct.

2023-03-29 18:29 UTC, shuoliugit commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +	} else if strings.Contains(status, "disabled") {
> else { set false }

The status must contain either "enabled" or "disabled". If not, there must be an error, and the code should have been errored out earlier.

2023-03-29 18:47 UTC, shuoliugit commented on aviatrix/resource_aviatrix_symmetric_routing_config.go
> +			"enable_symmetric_routing": {
> boolean attribute should have a default value.

It's a required attribute.

2023-04-14 16:49 UTC, zhiqiangjin approved these changes

2023-04-14 16:49 UTC, merged