AVX-36349: QoS class
AviatrixSystems/terraform-provider-aviatrix pull request #1713
Opened 2023-04-11 10:35 UTC by shuoliugit

2023-04-18 16:03 UTC, zhiqiangjin requested changes

2023-04-18 16:03 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_qos_policy.go
> +		ReadWithoutTimeout:   resourceAviatrixQosPolicyRead,
This is a list of policies, right? If yes, the resource name is misleading.

2023-04-18 16:03 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_qos_policy.go
> +			},
Is "uuid" per policy or per resource?

2023-04-19 23:00 UTC, shuoliugit commented on aviatrix/resource_aviatrix_qos_policy.go
> +			},
> Is "uuid" per policy or per resource?

per policy

2023-04-24 22:46 UTC, inc1t3Ful requested changes

2023-04-24 22:46 UTC, inc1t3Ful commented on docs/resources/aviatrix_qos_class.md
> +* `priority` - (Optional) Priority of QoS class.
mention that this accepts an integer.
```suggestion
* `priority` - (Optional) Priority of QoS class. Valid values: (integer)
```

2023-04-24 22:46 UTC, inc1t3Ful commented on docs/resources/aviatrix_qos_class.md
> +The **aviatrix_qos_class** resource creates the Aviatrix QoS Class.
```suggestion
The **aviatrix_qos_class** resource creates a class for the Quality of Service (QoS) mechanism in Aviatrix Edge. This feature allows classification based on DSCP value in IP Header.
```

You shouldn't use any abbreviation without first saying what it means.

2023-04-24 22:46 UTC, inc1t3Ful commented on docs/resources/aviatrix_qos_policy_list.md
> +The **aviatrix_qos_policy_list** resource creates the Aviatrix QoS Policy List.
```suggestion
The **aviatrix_qos_policy_list** resource creates a list of policies (and rules) under the Quality of Service (QoS) mechanism in Aviatrix Edge. This is to be used in conjunction with **aviatrix_qos_class**es to classify based on DSCP value in IP Header.
```

2023-04-24 22:48 UTC, inc1t3Ful commented on docs/resources/aviatrix_qos_policy_list.md
> +    qos_class_uuid = "efgh5678"
i think you can make one of the examples here have a dependency on the QoS class resource `uuid` / `.id` . That way its clear that its not just a random string

2023-04-24 22:49 UTC, inc1t3Ful commented on docs/resources/aviatrix_qos_policy_list.md
> +    qos_class_uuid = "efgh5678"
be sure to add an example QoS class resource within the snippet as well

2023-04-25 00:32 UTC, inc1t3Ful approved these changes

2023-04-26 03:43 UTC, zhiqiangjin approved these changes

2023-04-26 03:43 UTC, merged