AVX-38356: add test and doc for Edge NEO
AviatrixSystems/terraform-provider-aviatrix pull request #1734
Opened 2023-04-22 12:17 UTC by shuoliugit

2023-04-26 17:50 UTC, inc1t3Ful requested changes

2023-04-26 17:50 UTC, inc1t3Ful commented on docs/resources/aviatrix_edge_neo.md
> +    * `bandwidth` - (Optional) Bandwidth.
what is bandwidth? What type of values are accepted? Description isnt clear, esp since its not shown in the example code either

2023-04-26 17:50 UTC, inc1t3Ful commented on docs/resources/aviatrix_edge_csp_ha.md
>    * `bandwidth` - (Optional) Bandwidth.
what is bandwidth? What type of values are accepted? Description isnt clear, esp since its not shown in the example code either

2023-04-26 17:50 UTC, inc1t3Ful commented on docs/resources/aviatrix_edge_neo_ha.md
> +    * `bandwidth` - (Optional) Bandwidth.
what is bandwidth? What type of values are accepted? Description isnt clear, esp since its not shown in the example code either

2023-04-26 17:50 UTC, inc1t3Ful commented on docs/resources/aviatrix_edge_neo_ha.md
> +The **aviatrix_edge_neo_ha** resource creates the Aviatrix Edge NEO HA.
Are we to assume that in order to use this resource, we need the (primary) **aviatrix_edge_neo** first? If thats the case, we should make a note of that

2023-04-28 00:14 UTC, inc1t3Ful commented
Add what the measurement is for bandwidth. What does the integer represent? mbps? kbps? etc. Fix that for all relevant docs and it should be good

2023-04-28 00:15 UTC, inc1t3Ful requested changes
Address the above comment regarding bandwidth

2023-04-28 02:08 UTC, inc1t3Ful submitted a review, later dismissed
LGTM

2023-04-28 16:23 UTC, zhiqiangjin approved these changes

2023-04-28 16:23 UTC, merged