Update gateway and s2c docs
AviatrixSystems/terraform-provider-aviatrix pull request #178
Opened 2019-11-20 21:40 UTC by inc1t3Ful

** standardize formatting
** move notes within each attribute
++ references to s2c doc site for HA workflow

2019-11-20 22:04 UTC, arvindsree approved these changes

2019-11-20 22:06 UTC, arvindsree requested changes
Keep the note towards the end. It looks weird https://github.com/terraform-providers/terraform-provider-aviatrix/blob/098972e9390087e5a7a57d533e35cd03f072eb10/website/docs/r/aviatrix_gateway.html.markdown
you can add a reference links to the note within the parameter if required

2019-11-20 23:30 UTC, inc1t3Ful commented
> Keep the note towards the end. It looks weird https://github.com/terraform-providers/terraform-provider-aviatrix/blob/098972e9390087e5a7a57d533e35cd03f072eb10/website/docs/r/aviatrix_gateway.html.markdown
> you can add a reference links to the note within the parameter if required

Sure. I'm only following what AWS does for their docs. For example:
https://www.terraform.io/docs/providers/aws/index.html#ignore_tag_prefixes

2019-11-21 01:57 UTC, arvindsree approved these changes

2019-11-21 01:58 UTC, merged