AVX-44451: add support of spot instance for azure
AviatrixSystems/terraform-provider-aviatrix pull request #1849
Opened 2023-08-11 21:41 UTC by shuoliugit

2023-08-14 20:07 UTC, avtx-akonnur reviewed
Does this add the optional argument of `--delete_spot`? only for Azure spot GW creation?

2023-08-22 17:41 UTC, zhiqiangjin requested changes

2023-08-22 17:41 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_gateway.go
> +			"delete_spot": {
"spot instance" support is only for internal test use. Should NOT be exposed in terraform state if not used.

2023-08-22 18:27 UTC, avtx-akonnur reviewed
Thanks for adding the delete spot argument, I will let @zhiqiangjin approve the PR.

2023-10-16 18:15 UTC, zhiqiangjin approved these changes

2023-10-16 18:15 UTC, merged