AVX-53193 - Update Vendor integration data source doc
AviatrixSystems/terraform-provider-aviatrix pull request #1977
Opened 2024-05-06 23:29 UTC by inc1t3Ful

# Changes
- Update Vendor Integration data source doc examples for AWS and Azure
- Update `instance_id` example for Azure
- Update description for `vpc_id`

2024-05-07 07:12 UTC, Dennizz requested changes
Can you please add the example to the arguments section as well, just like you have done for the vpc_id? E.g.: 

`instance_id` - (Required) ID of Firewall instance. Example: AWS: "i-09ade2592661316f8", Azure: "firewall_instance_name:resource_group_name"

Thanks

2024-05-07 21:42 UTC, inc1t3Ful commented
Done

2024-05-08 07:54 UTC, Dennizz approved these changes
Perfect. Thanks!

2024-05-08 07:55 UTC, Dennizz approved these changes

2024-05-08 20:12 UTC, dnardo approved these changes

2024-05-08 20:13 UTC, merged