AVX-54790 Adding BGP BFD config to external connection
AviatrixSystems/terraform-provider-aviatrix pull request #2051
Opened 2024-09-18 18:22 UTC by sairane10

Updating the following resource with bgp_bfd config
- aviatrix_edge_spoke_external_device_conn
- avaitrix_transit_external_device_conn

Example of the connection resource with BGP-BFD enabled
```
`resource "aviatrix_transit_external_device_conn" "transit-1-transit-2" {
  vpc_id            = "vpc-048eb7341becf3c1b"
  connection_name   = "transit-1-transit-2"
  gw_name           = "udxjl-aws-transit-1"
  connection_type   = "bgp"
  tunnel_protocol    = "IPsec"
  bgp_local_as_num  = "65075"
  bgp_remote_as_num = "65076"
  remote_gateway_ip = "3.19.43.179"
  local_tunnel_cidr  = "169.254.10.1/30"
  remote_tunnel_cidr = "169.254.10.2/30"
  pre_shared_key = "psk12"
  enable_bfd = true
  bgp_bfd {
    transmit_interval = 500
    receive_interval = 500
    multiplier = 5
  }
}

resource "aviatrix_transit_external_device_conn" "transit-2-transit-1" {
  vpc_id            = "vpc-00951e22f3e587165"
  connection_name   = "transit-2-transit-1"
  gw_name           = "udxjl-aws-transit-2"
  connection_type   = "bgp"
  tunnel_protocol    = "IPsec"
  bgp_local_as_num  = "65076"
  bgp_remote_as_num = "65075"
  remote_gateway_ip = "3.140.172.87"
  local_tunnel_cidr  = "169.254.10.2/30"
  remote_tunnel_cidr = "169.254.10.1/30"
  pre_shared_key = "psk12"
}

resource "aviatrix_edge_spoke_external_device_conn" "edge_bgp_lan" {
  site_id                  = "SC"
  connection_name          = "cloudn-bgp-lan"
  gw_name                  = "Edge-182"
  bgp_local_as_num         = "65182"
  bgp_remote_as_num        = "65220"
  local_lan_ip             = "10.220.86.182"
  remote_lan_ip            = "10.220.86.100"
  enable_bfd               = true
  bgp_bfd {
    transmit_interval = 400
    receive_interval = 400
    multiplier = 5
  }
}`
```

2024-09-27 19:47 UTC, stewartbutler requested changes
I'd like to see some tests and comments, also I'm not sure you are checking all the type assertions that are needed.

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +				bfd1 := bfd0.(map[string]interface{})
Check type assertion?

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +		bgp_bfd := d.Get("bgp_bfd").([]interface{})
Check type assertion?

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +	enable_bfd := d.Get("enable_bfd").(bool)
Check type assertion?

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +	enableBfd := d.Get("enable_bfd").(bool)
Check assertion

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +		bgpBfdConfig := d.Get("bgp_bfd").([]interface{})
Check

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +			if bfdConfig["transmit_interval"].(int) == 0 {
Are there situations where any of these would legitimately be zero?

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +			if bfd.TransmitInterval != 0 {
Any situations where this would really be zero?

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_transit_external_device_conn.go
> +		bgp_bfd := d.Get("bgp_bfd").([]interface{})
Check type assertion? 

(Last one I'll comment on)

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_transit_external_device_conn.go
> +				if value, ok := bfd1["transmit_interval"].(int); ok && value != 0 {
Any times where value can really be zero?

(Last time I'll comment on this)

2024-09-27 19:47 UTC, stewartbutler commented on goaviatrix/transit_external_device_conn.go
> +func (c *Client) EditConnectionBgpBfd(externalDeviceConn *ExternalDeviceConn) error {
Tests?

2024-09-27 19:47 UTC, stewartbutler commented on goaviatrix/transit_external_device_conn.go
> +	BgpBfdConfig           []*BgpBfdConfig `json:"bgp_bfd,omitempty"`
`json`? Or should this be `form`?

2024-09-27 19:47 UTC, stewartbutler commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +	enableBFD := d.Get("enable_bfd").(bool)
Tests?

2024-09-30 17:54 UTC, sairane10 commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +				bfd1 := bfd0.(map[string]interface{})
Added the change

2024-09-30 17:54 UTC, sairane10 commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +	enable_bfd := d.Get("enable_bfd").(bool)
updated

2024-09-30 17:54 UTC, sairane10 commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +		bgpBfdConfig := d.Get("bgp_bfd").([]interface{})
updated

2024-09-30 17:54 UTC, sairane10 commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +		bgp_bfd := d.Get("bgp_bfd").([]interface{})
updated

2024-09-30 17:55 UTC, sairane10 commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +	enableBfd := d.Get("enable_bfd").(bool)
updated

2024-09-30 17:55 UTC, sairane10 commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +			if bfdConfig["transmit_interval"].(int) == 0 {
Updated the code to handle empty values.

2024-09-30 17:57 UTC, sairane10 commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +			if bfd.TransmitInterval != 0 {
This checks if the int value if set for bgp_bfd config. If the values are not set then use the default values where enable_bfd is set to true.

2024-09-30 17:57 UTC, sairane10 commented on aviatrix/resource_aviatrix_transit_external_device_conn.go
> +		bgp_bfd := d.Get("bgp_bfd").([]interface{})
updated

2024-09-30 17:57 UTC, sairane10 commented on goaviatrix/transit_external_device_conn.go
> +	BgpBfdConfig           []*BgpBfdConfig `json:"bgp_bfd,omitempty"`
updated

2024-09-30 17:58 UTC, sairane10 commented on aviatrix/resource_aviatrix_transit_external_device_conn.go
> +				if value, ok := bfd1["transmit_interval"].(int); ok && value != 0 {
Updated the code to handle empty values in interfaces

2024-09-30 20:35 UTC, sairane10 commented on goaviatrix/transit_external_device_conn.go
> +func (c *Client) EditConnectionBgpBfd(externalDeviceConn *ExternalDeviceConn) error {
Added tests

2024-09-30 20:35 UTC, sairane10 commented on aviatrix/resource_aviatrix_edge_spoke_external_device_conn.go
> +	enableBFD := d.Get("enable_bfd").(bool)
Added tests

2024-09-30 22:11 UTC, stewartbutler commented on aviatrix/resource_aviatrix_transit_external_device_conn_test.go
> +	single_az_ha = true
nit: Inconsistent tab/space prefixing

2024-09-30 22:11 UTC, stewartbutler approved these changes
LGTM

2024-09-30 23:16 UTC, merged