AVX-58209 Updating the transit gateway with bgp-bfd polling time
AviatrixSystems/terraform-provider-aviatrix pull request #2089
Opened 2024-10-29 18:02 UTC by sairane10

This bug fixes the missing bgp-bfd polling time in transit gateway. This change got overridden while merging conflicts

2024-10-30 18:50 UTC, inc1t3Ful requested changes
Please update missing documentation for this new attribute in the transit gateway doc

2024-10-30 18:52 UTC, inc1t3Ful commented
I noticed since you changed the `bgp_polling_time` to Int type, did you test how that would affect existing resource?

aka if a transit was created prior to this change with `bgp_polling_time` set (as string), and then when they update their provider with this new change to Int type, will they get a delta/will there be any issues?

2024-10-30 21:44 UTC, sairane10 commented
@inc1t3Ful This documentation change are already a part of this merged PR - https://github.com/AviatrixSystems/terraform-provider-aviatrix/pull/2048
I had a transit deployed with bgp_polling_time set as a string value. On applying this change it showed a delta on the existing resource but there no issues encountered.

2024-10-30 23:16 UTC, inc1t3Ful commented
@sairane10 On applying the code change, it shows a delta which is expected. But will the existing resource delta be resolved in the TF apply? As in, if on your next TF operation (apply), will that delta still be shown? 

I assume after that users would have to normally just change their infra code from "50" to 50?

2024-10-31 16:09 UTC, sairane10 commented
@inc1t3Ful On my TF apply operation the delta was show as I had to change the value to int instead of a string. The users will have to manually apply this change.

2024-11-01 00:36 UTC, inc1t3Ful commented
> @inc1t3Ful This documentation change are already a part of this merged PR - #2048 I had a transit deployed with bgp_polling_time set as a string value. On applying this change it showed a delta on the existing resource but there no issues encountered.

Can we also update the R3.x Feature Changelist doc and ensure that this data type change is noted? Please go create a table for R3.2.1 (I assume it is for that version release), and list the "Diff" column as "(changed)" , where "Action Required" is "Yes; ... "  and provide note/instruction on what the user should do.

You can also refer to the R2.x Feature Changelist for reference if you are unsure about the wording. 
- https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/guides/feature-changelist-v2#boolean-standardization

2024-11-01 21:04 UTC, sairane10 commented
@inc1t3Ful Added the feature changelist document update.

2024-11-01 21:12 UTC, inc1t3Ful requested changes

2024-11-01 21:12 UTC, inc1t3Ful commented on docs/guides/feature-changelist-v3.md
> +## R3.2.1 (UserConnect-7.2)**
```suggestion
## R3.2.1 (UserConnect-7.2)
```

2024-11-01 21:15 UTC, inc1t3Ful approved these changes
LGTM

2024-11-01 21:15 UTC, merged