Add 4 new transit gateway advanced config options
AviatrixSystems/terraform-provider-aviatrix pull request #481
Opened 2020-07-14 19:54 UTC by CyrusJavan

4 new advanced config options for the transit_gateway resource
 - bgp_polling_time
 - prepend_as_path
 - local_as_number
 - bgp_ecmp

NOTE: `local_as_number` is one the edge cases where an attribute can be set, but never unset. So if you were to have the value set in your config, then remove it and apply, in reality the value is still set. Thus if you were to them remove the resource from state and import, the `local_as_number` value would still be imported.

2020-07-14 19:57 UTC, CyrusJavan commented
Also @zhiqiangjin I am trying out an abstraction with the `PostAPI` function, please let me know if it makes sense to you. My reasoning for it is that we have duplicated the code for decoding an API response, and checking the Return field many times in the code so I thought an abstraction like this could reduce some of the repeated code. 

Let me know what you think please!

2020-07-14 20:27 UTC, zhiqiangjin requested changes

2020-07-14 20:27 UTC, zhiqiangjin commented on aviatrix/provider.go
> +func validateIntASN() schema.SchemaValidateFunc {
Move this validateIntASN function under /goaviatrix

2020-07-14 20:27 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_gateway.go
> +				Type:         schema.TypeInt,
Change type to String instead of Int. String is used for ASN in all other resources.

2020-07-14 20:27 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_transit_gateway.go
> +				Type:         schema.TypeInt,
Change type to String instead of Int. I think we only use TypeInt for cloud_type.

2020-07-15 00:31 UTC, zhiqiangjin approved these changes

2020-07-15 00:31 UTC, merged