(16147) Add fqdn_pass_through resource
AviatrixSystems/terraform-provider-aviatrix pull request #492
Opened 2020-07-23 19:20 UTC by CyrusJavan

Add FQDN Pass-Through resource

2020-07-27 16:33 UTC, CyrusJavan commented
This name was approved by Sherry. @zhiqiangjin

2020-07-27 21:32 UTC, zhiqiangjin requested changes

2020-07-27 21:32 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_fqdn_pass_through.go
> +	for _, cidr := range cidrs {
Here maybe have reordering issue. Please verify.

2020-07-27 21:32 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_fqdn_pass_through.go
> +	if d.HasChange("pass_through_cidrs") {
What if only the order of pass_through_cidrs changed?

2020-07-28 00:53 UTC, zhiqiangjin approved these changes

2020-07-28 00:53 UTC, merged