18245: public subnet filtering gateway
AviatrixSystems/terraform-provider-aviatrix pull request #647
Opened 2020-11-10 18:29 UTC by CyrusJavan

This PR adds the ability to create and manage
a public subnet filtering gateway.

We do this by adding some additional options
to the gateway resource. Still to do is adding
support for these new options in TF Export.

2020-11-12 00:08 UTC, inc1t3Ful commented
Docs are good 👍  I think Tim wanted to re-discuss implementation choices at some point

2020-12-01 06:23 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_gateway.go
> +var invalidPublicSubnetFilteringGatewayConfigKeys = []string{
Move "invalidPublicSubnetFilteringGatewayConfigKeys" to the bottom.

2020-12-01 06:28 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_gateway.go
> +			"public_subnet_filtering": {
Maybe change to "enable_public_subnet_filtering" or "public_subnet_filtering_enabled"?

2020-12-01 06:30 UTC, zhiqiangjin requested changes
Probably need to change "public_subnet_filtering" to "enable_public_subnet_filtering" or "public_subnet_filtering_enabled".

2020-12-02 05:45 UTC, zhiqiangjin approved these changes

2020-12-02 05:46 UTC, merged