18245: Add aws_guard_duty resource
AviatrixSystems/terraform-provider-aviatrix pull request #648
Opened 2020-11-11 18:09 UTC by CyrusJavan

2020-12-01 06:37 UTC, zhiqiangjin requested changes

2020-12-01 06:37 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_aws_guard_duty.go
> +func marshalAwsGuardDutyInput(d *schema.ResourceData) *goaviatrix.AwsGuardDuty {
Move this function to the bottom.

2020-12-01 06:37 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_aws_guard_duty.go
> +	return nil
Should be "return resourceAviatrixGatewayRead(d, meta)"?

2020-12-01 06:37 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_aws_guard_duty.go
> +	return nil
Should return resourceAviatrixGatewayRead(d, meta)?

2020-12-02 18:05 UTC, CyrusJavan commented
@zhiqiangjin I added `defer Read(d, meta)` to both the Update and Create.

2020-12-08 05:05 UTC, zhiqiangjin approved these changes

2020-12-08 05:05 UTC, merged