19529: add support for controller backup
AviatrixSystems/terraform-provider-aviatrix pull request #766
Opened 2021-02-10 11:51 UTC by shuoliugit

2021-02-10 22:12 UTC, CyrusJavan requested changes

2021-02-10 22:12 UTC, CyrusJavan commented on goaviatrix/controller.go
> +		return err
Why add the extra line to assign to a variable before returning? Does not seem more clear to me

2021-02-10 22:12 UTC, CyrusJavan commented on goaviatrix/controller.go
> +func ValidateBackupConfig(d *schema.ResourceData) error {
This function should not be in `goaviatrix` package. This is specific to the resource schema and should be in the controller config resource file.

2021-02-10 22:12 UTC, CyrusJavan commented on docs/resources/aviatrix_controller_config.md
> +* `backup_region` - (Optional) Name of region. Required for Azure and OCI.
Required **to enable configuration backup** for AWS, AWSGOV, GCP and OCI.

2021-02-10 22:12 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_controller_config.go
> +			backupConfigErr := goaviatrix.ValidateBackupConfig(d)
We should follow the pattern that is used throughout the code base and use the variable name `err` for error returns.

2021-02-10 22:12 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_controller_config.go
> +		backupConfigErr := goaviatrix.ValidateBackupConfig(d)
We should follow the pattern that is used throughout the code base and use the variable name `err` for error returns.

2021-02-11 18:18 UTC, CyrusJavan approved these changes

2021-02-12 04:16 UTC, zhiqiangjin approved these changes

2021-02-12 04:16 UTC, merged