20635: Add max bgp hop limit for non-rfc1918 cidrs
AviatrixSystems/terraform-provider-aviatrix pull request #851
Opened 2021-03-19 15:12 UTC by mlin-aviatrix

2021-03-22 19:16 UTC, CyrusJavan requested changes

2021-03-22 19:16 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_controller_bgp_max_as_limit_config.go
>  	client := meta.(*goaviatrix.Client)
We should do this same validation in update:
```go
if !maxAsLimitOk && !maxAslimitNonRfc1918Ok {
		return diag.Errorf("error updating controller BGP max AS limit config: at least one of max_as_limit and max_as_limit_non_rfc1918 must be provided")
	}
```

2021-03-22 19:16 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_controller_bgp_max_as_limit_config.go
> +			}
These error strings need to be unique, same below

2021-03-22 19:16 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_controller_bgp_max_as_limit_config.go
> +			maxAsLimit := d.Get("max_as_limit").(int)
Why not just get the maxAsLimit when you call GetOk above?

2021-03-22 19:16 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_controller_bgp_max_as_limit_config_test.go
> +	max_as_limit_non_rfc1918 = 2
formatting

2021-03-22 19:16 UTC, CyrusJavan commented on docs/resources/aviatrix_controller_bgp_max_as_limit_config.md
> +  max_as_limit_non_rfc1918 = 2
formatting

2021-03-22 19:16 UTC, CyrusJavan commented on goaviatrix/controller_bgp_max_as_limit_config.go
> +		maxAsLimit = 0
not needed, in Go values are initialized to their zero value, maxAsLimit is already `0`

2021-03-22 22:32 UTC, mlin-aviatrix commented on aviatrix/resource_aviatrix_controller_bgp_max_as_limit_config_test.go
> +	max_as_limit_non_rfc1918 = 2
What needs to be changed here?

2021-03-22 22:54 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_controller_bgp_max_as_limit_config_test.go
> +	max_as_limit_non_rfc1918 = 2
Just need to line up the `=`

2021-03-23 19:46 UTC, CyrusJavan approved these changes
Good job!

2021-03-25 17:37 UTC, zhiqiangjin approved these changes

2021-03-25 17:37 UTC, merged