20395: Added ARMGOV (32) to supported clouds and added support for ARMGOV accounts
AviatrixSystems/terraform-provider-aviatrix pull request #867
Opened 2021-03-29 19:52 UTC by mlin-aviatrix

2021-03-29 22:27 UTC, CyrusJavan approved these changes, later dismissed

2021-03-29 22:27 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_account_test.go
> +resource "aviatrix_account" "armgov" {
Line up `=`

2021-03-29 22:27 UTC, CyrusJavan commented on docs/resources/aviatrix_account.md
> +resource "aviatrix_account" "temp_acc_armgov" {
Line up `=`

2021-03-30 22:35 UTC, zhiqiangjin approved these changes, later dismissed

2021-03-30 22:40 UTC, shuoliugit approved these changes, later dismissed

2021-03-31 08:46 UTC, zhiqiangjin requested changes

2021-03-31 08:46 UTC, zhiqiangjin commented on aviatrix/data_source_aviatrix_account.go
> +			"armgov_subscription_id": {
Should we use azure_gov_subscription_id?

2021-03-31 08:46 UTC, zhiqiangjin commented on aviatrix/resource_aviatrix_account.go
> +			"armgov_subscription_id": {
Same for following four attributes: should we use azure_gov_subscription_id?

2021-03-31 08:46 UTC, zhiqiangjin commented on goaviatrix/account.go
> +	ArmgovSubscriptionId                  string `form:"azure_gov_subscription_id,omitempty" json:"arm_gov_subscription_id,omitempty"`
Same here.

2021-03-31 08:46 UTC, zhiqiangjin commented on goaviatrix/const.go
> +	ARMGOV = 32
Maybe: AzureGOV

2021-04-06 20:58 UTC, zhiqiangjin approved these changes

2021-04-06 20:58 UTC, merged