20888: implemented aviatrix_aws_tgw_security_domain_connection
AviatrixSystems/terraform-provider-aviatrix pull request #879
Opened 2021-04-06 14:38 UTC by shuoliugit

2021-04-07 00:01 UTC, CyrusJavan requested changes

2021-04-07 00:01 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_aws_tgw_security_domain_connection.go
> +	}
Nit: From the implementation of strings.Compare, it seems we should just use `sourceDomainName < destinationDomainName`

```go
// Compare returns an integer comparing two strings lexicographically.
// The result will be 0 if a==b, -1 if a < b, and +1 if a > b.
//
// Compare is included only for symmetry with package bytes.
// It is usually clearer and always faster to use the built-in
// string comparison operators ==, <, >, and so on.
func Compare(a, b string) int {
	// NOTE(rsc): This function does NOT call the runtime cmpstring function,
	// because we do not want to provide any performance justification for
	// using strings.Compare. Basically no one should use strings.Compare.
	// As the comment above says, it is here only for symmetry with package bytes.
	// If performance is important, the compiler should be changed to recognize
	// the pattern so that all code doing three-way comparisons, not just code
	// using strings.Compare, can benefit.
	if a == b {
		return 0
	}
	if a < b {
		return -1
	}
	return +1
}
```

2021-04-07 00:01 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_aws_tgw_security_domain_connection.go
> +		if strings.Compare(sourceDomainName, destinationDomainName) == -1 {
Same as above

2021-04-07 00:01 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_aws_tgw_security_domain_connection.go
> +		return diag.Errorf("couldn't get the details of the security domain %s due to %v", sourceDomainName, err)
Let's stick with the same pattern for errors found in other parts of the code, using a colon to separate the error
```go
return diag.Errorf("could not get the details of the security domain %s: %v", sourceDomainName, err)
```

2021-04-07 00:01 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_aws_tgw_security_domain_connection.go
> +			if strings.Compare(sourceDomainName, destinationDomainName) == -1 {
Same as above

2021-04-07 00:01 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_aws_tgw_security_domain_connection_test.go
> +}
Line up equals signs.

2021-04-07 00:01 UTC, CyrusJavan commented on docs/resources/aviatrix_aws_tgw_security_domain.md
> +}
This one is repeat from above

2021-04-14 22:34 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_aws_tgw_security_domain_connection.go
> +	if err != nil && err != goaviatrix.ErrNotFound {
What is err == ErrNotFound?

2021-04-14 23:10 UTC, CyrusJavan approved these changes

2021-04-14 23:16 UTC, zhiqiangjin approved these changes

2021-04-14 23:16 UTC, merged