20985: Add single ip ha to site2cloud
AviatrixSystems/terraform-provider-aviatrix pull request #902
Opened 2021-04-16 06:10 UTC by mlin-aviatrix

2021-04-16 21:54 UTC, CyrusJavan requested changes
Can you check if this feature is specifically for the site2cloud connection only OR for all site2cloud (IPsec) type connections, which would include
- site2cloud
- transit_external_device_conn
- vgw_conn
- device_transit_gateway_attachment

Most likely it is for all these resources so this would need to be added to all of them. See #873 for example.

2021-04-17 00:18 UTC, zhiqiangjin submitted a review, later dismissed

2021-04-17 13:38 UTC, shuoliugit approved these changes, later dismissed

2021-04-20 19:59 UTC, mlin-aviatrix commented
This is only for site2cloud for now. Not the other IPSec type connections

2021-04-20 21:48 UTC, zhiqiangjin approved these changes

2021-04-20 22:31 UTC, CyrusJavan approved these changes

2021-04-21 00:34 UTC, merged