Rename cloud constants to have consistent cloud provider names
AviatrixSystems/terraform-provider-aviatrix pull request #907
Opened 2021-04-20 19:25 UTC by mlin-aviatrix

2021-04-20 22:34 UTC, CyrusJavan requested changes

2021-04-20 22:34 UTC, CyrusJavan commented on docs/resources/aviatrix_account.md
> +<<<<<<< HEAD
clean up please.

2021-04-20 22:34 UTC, CyrusJavan commented on docs/resources/aviatrix_account.md
> +<<<<<<< HEAD
clean up please.

2021-04-20 23:10 UTC, CyrusJavan approved these changes

2021-04-21 07:59 UTC, zhiqiangjin approved these changes

2021-04-21 07:59 UTC, merged