21713: added tgw_id
AviatrixSystems/terraform-provider-aviatrix pull request #915
Opened 2021-04-23 06:09 UTC by shuoliugit

2021-04-23 17:46 UTC, CyrusJavan requested changes

2021-04-23 17:46 UTC, CyrusJavan commented on docs/resources/aviatrix_aws_tgw.md
> +* `tgw_id`- TGW ID. Available as of provider version R2.19+.
```suggestion
* `tgw_id` - TGW ID. Available as of provider version R2.19+.
```

2021-04-23 20:17 UTC, CyrusJavan approved these changes

2021-04-24 00:39 UTC, zhiqiangjin approved these changes

2021-04-24 00:39 UTC, merged