22222: add local_subnet to transit_external_device_conn
AviatrixSystems/terraform-provider-aviatrix pull request #970
Opened 2021-05-21 19:38 UTC by shuoliugit

2021-05-21 21:09 UTC, CyrusJavan requested changes

2021-05-21 21:09 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_transit_external_device_conn.go
> +		editSite2cloud.NetworkType = "1"
```suggestion
		editSite2cloud := &goaviatrix.EditSite2Cloud{
			GwName:   gwName,
			VpcID:    d.Get("vpc_id").(string),
			ConnName: connName,
			CloudSubnetCidr: d.Get("local_subnet").(string),
			NetworkType: "1",
		}
```

2021-05-22 00:18 UTC, CyrusJavan approved these changes

2021-05-26 16:50 UTC, zhiqiangjin approved these changes

2021-05-26 16:50 UTC, merged