22363: Add new resource aviatrix_controller_gateway_keepalive_config …
AviatrixSystems/terraform-provider-aviatrix pull request #990
Opened 2021-06-08 20:23 UTC by mlin-aviatrix

…for gateway keepalive speed

2021-06-08 21:00 UTC, CyrusJavan requested changes

2021-06-08 21:00 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_controller_gateway_keepalive_config.go
> +		DeleteContext: resourceControllerGatewayKeepaliveConfigDelete,
Let's use the WithoutTimeout versions.

2021-06-08 21:00 UTC, CyrusJavan commented on aviatrix/resource_aviatrix_controller_gateway_keepalive_config.go
> +			"keep_alive_speed": {
Let's be consistent in the naming, the resource uses keepalive not keep_alive

2021-06-17 21:02 UTC, CyrusJavan approved these changes

2021-06-17 21:16 UTC, zhiqiangjin approved these changes

2021-06-17 21:16 UTC, merged